backend/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, :only => [:show]
  resources :items
  resources :locations
  resources :foods

end

backend/app/models/food.rb
class Food < ActiveRecord::Base
  validates :name, {uniqueness: true, presence: true}
  validates :store, presence: true
  validates :price, presence: true, numericality: true
  validates :quantity, presence: true, numericality: true
  validates :end_level, presence: true, numericality: true
  has_many :Items
end

backend/app/models/item.rb
class Item < ActiveRecord::Base
  validates :onload_year, presence: true
  validates :onload_week, presence: true
  validates :onload_day, presence: true
  validates :onload_by, presence: true
  validates :best_before, presence: true
  validates :food, presence: true
  validates :location, presence: true
  belongs_to :food
  belongs_to :location
end

backend/app/models/location.rb
class Location < ActiveRecord::Base
  validates :name, {uniqueness: true, presence: true}
  validates :position, presence: true
  validates :deck, presence: true
  validates :rack, presence: true
  validates :store_type, presence: true


  has_many :locations
end

backend/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, {uniqueness: true, presence: true}
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  respond_to :json, :html
  protect_from_forgery with: :null_session
end

backend/app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
    render :json => @foods, :only => [:id, :name, :store]
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :store, :quantity, :quantity_type, :end_level, :price)
    end
end

backend/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    render :json => @items, :include =>[{:location =>{:except=>[:id, :created_at, :updated_at]}}, {:food =>{:except =>[:id, :created_at, :updated_at]}}], :except => [:created_at, :updated_at, :food_id, :location_id]
  end

  # GET /items/1
  # GET /items/1.json
  def show
   
   render status: 200, :json => @item

  end

  def new
    @item = Item.new
    @foods = Food.all
    @locations = Location.all
  end

  

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
        @item = Item.new(item_params)
        if @item.save
        @items = Item.all
        render status: 201, :json => @item
       
        else
          render status: 404,  json: { message: @item.errors}.to_json
        end
    
    
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    if @item.update(item_params)
   render status: 201, :json => @item, :include =>[{:location =>{:except=>[:id, :created_at, :updated_at]}}, {:food =>{:except =>[:id, :created_at, :updated_at]}}], :except => [:created_at, :updated_at, :food_id, :location_id]
    else
      render status: 404,  json: { message: @item.errors}.to_json
    end

    
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    @items = Item.all
    render :json => @items, :include =>[{:location =>{:except=>[:id, :created_at, :updated_at]}}, {:food =>{:except =>[:id, :created_at, :updated_at]}}], :except => [:created_at, :updated_at, :food_id, :location_id]
    
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:food_id, :location_id, :best_before, :onload_year, :onload_week, :onload_day, :onload_by, :offload_year, :offload_week, :offload_day, :offload_by)
    end
end

backend/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    render :json => @locations, :only => [:id, :name, :store_type]
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :deck, :position, :rack, :store_type)
    end
end

backend/app/controllers/users_controller.rb
class UsersController < ApplicationController

  respond_to :json

    def show
      respond_with User.find(params[:id])
    end

end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/foods_helper.rb
module FoodsHelper
end

backend/app/helpers/items_helper.rb
module ItemsHelper
end

backend/app/helpers/locations_helper.rb
module LocationsHelper
end

backend/app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :store %><br>
    <%= f.text_field :store %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :quantity_type %><br>
    <%= f.text_field :quantity_type %>
  </div>
  <div class="field">
    <%= f.label :end_level %><br>
    <%= f.text_field :end_level %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

backend/app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Foods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Store</th>
      <th>Quantity</th>
      <th>Quantity type</th>
      <th>End level</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.store %></td>
        <td><%= food.quantity %></td>
        <td><%= food.quantity_type %></td>
        <td><%= food.end_level %></td>
        <td><%= food.price %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

backend/app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

backend/app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Store:</strong>
  <%= @food.store %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @food.quantity %>
</p>

<p>
  <strong>Quantity type:</strong>
  <%= @food.quantity_type %>
</p>

<p>
  <strong>End level:</strong>
  <%= @food.end_level %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food.price %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

backend/app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :food_id %><br>
    <%= f.collection_select(:food_id, @foods, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.collection_select(:location_id, @locations, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :best_before %><br>
    <%= f.date_select :best_before %>
  </div>
  <div class="field">
    <%= f.label :onload_year %><br>
    <%= f.option_select :onload_year %>
  </div>
  <div class="field">
    <%= f.label :onload_week %><br>
    <%= f.date_select :onload_year %>
  </div>
  <div class="field">
    <%= f.label :onload_by %><br>
    <%= f.text_field :onload_by %>
  </div>
  <div class="field">
    <%= f.label :offload_date %><br>
    <%= f.date_select :offload_date %>
  </div>
  <div class="field">
    <%= f.label :offload_by %><br>
    <%= f.text_field :offload_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

backend/app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Location</th>
      <th>Best before</th>
      <th>Onload date</th>
      <th>Onload by</th>
      <th>Offload date</th>
      <th>Offload by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.food %></td>
        <td><%= item.location %></td>
        <td><%= item.best_before %></td>
        <td><%= item.onload_date %></td>
        <td><%= item.onload_by %></td>
        <td><%= item.offload_date %></td>
        <td><%= item.offload_by %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

backend/app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

backend/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food:</strong>
  <%= @item.food %>
</p>

<p>
  <strong>Location:</strong>
  <%= @item.location %>
</p>

<p>
  <strong>Best before:</strong>
  <%= @item.best_before %>
</p>

<p>
  <strong>Onload date:</strong>
  <%= @item.onload_date %>
</p>

<p>
  <strong>Onload by:</strong>
  <%= @item.onload_by %>
</p>

<p>
  <strong>Offload date:</strong>
  <%= @item.offload_date %>
</p>

<p>
  <strong>Offload by:</strong>
  <%= @item.offload_by %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Backend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

backend/app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :deck %><br>
    <%= f.text_field :deck %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :rack %><br>
    <%= f.text_field :rack %>
  </div>
  <div class="field">
    <%= f.label :store_type %><br>
    <%= f.text_field :store_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

backend/app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Deck</th>
      <th>Position</th>
      <th>Rack</th>
      <th>Store type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= location.deck %></td>
        <td><%= location.position %></td>
        <td><%= location.rack %></td>
        <td><%= location.store_type %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

backend/app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

backend/app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Deck:</strong>
  <%= @location.deck %>
</p>

<p>
  <strong>Position:</strong>
  <%= @location.position %>
</p>

<p>
  <strong>Rack:</strong>
  <%= @location.rack %>
</p>

<p>
  <strong>Store type:</strong>
  <%= @location.store_type %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>